### ISSUE TITLE
DB data does not persist

### ISSUE THREAD

**Issue by timkelty** [webdevops/php-docker-boilerplate#67]
When I bring a container down, I lose my data.
Surely this isn't expected?

Don't we need a volume for `/var/lib/mysql`?

**Comment by timkelty** [comment]
Adding a mysql volume remedied this, but are you intending for people to use the storage container for this?

```
version: '2'
services:
  mysql:
    build:
      context: docker/mysql/
      dockerfile: MySQL-5.7.Dockerfile
    ports:
      - 13306:3306
    volumes:
      - mysql:/var/lib/mysql
    env_file:
      - etc/environment.yml
      - etc/environment.development.yml
volumes:
  mysql:

```
