### ISSUE TITLE
How do I install WordPress?

### ISSUE THREAD

**Issue by mkoseoglu** [webdevops/php-docker-boilerplate#68]
Hello to everyone. 
I want to install WordPress inside the `app` directory. But `mySQL` does not accept the information. Can you help with this?

**Comment by mblaschke** [comment]
Which connection settings have you tried?

Hostname: `mysql`
User: `root` (or `dev`)
Password: `dev`
Database: `database`

**Comment by mkoseoglu** [comment]
Hi @mblaschke,

Thank u for responsive my issue. 

Yes, it worked when I wrote `mysql`. This is definitely my mistake. I wrote `"hostname: localhost"`. So where do I change the "`mysql`" name there?

**Comment by mblaschke** [comment]
The name `mysql` is coming from the name of the `mysql` container. If you change the name inside the `docker-compose.yml` file the hostname of the container will also be changed.

Each container is an own server environment (sandboxed) with it's own ip address.

And that's why you should use the hostname `mysql` for connecting to the mysql database which runs in a container :)

**Comment by mkoseoglu** [comment]
Yes I understood. I have one more question. Do I also need to type "links: -phpmyadmin" in the "docker-compose.yml" file? So, the code below is correct?

```
version: '2'
services:
  #######################################
  # PHP application Docker container
  #######################################
  app:
    build:
      context: .
      dockerfile: Dockerfile.development
    links:
       - mysql
       - phpmyadmin
    ports:
      - "8000:80"
      - "8443:443"
      - "10022:22"
    volumes:
      - ./app/:/app/
      - ./:/docker/
    # cap and privileged needed for slowlog
    cap_add:
      - SYS_PTRACE
    privileged: true
    env_file:
      - etc/environment.yml
      - etc/environment.development.yml
    environment:
      - VIRTUAL_HOST=.app.boilerplate.docker
      - VIRTUAL_PORT=80
      - POSTFIX_RELAYHOST=[mail]:1025
```
